services:
  - type: web
    name: whatsapp-automation
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: PUPPETEER_HEADLESS
        value: true
    healthCheckPath: /api/health